# Generated by Django 6.0.3 on 2026-04-02 10:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.FloatField()),
                ("motif", models.TextField(blank=True, null=True)),
                ("date_demande", models.DateField(default=datetime.date.today)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvée"),
                            ("refuse", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("notes_admin", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="approved_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "salary_advance",
                "ordering": ["-created_at"],
            },
        ),
    ]
