# Generated by Django 6.0.3 on 2026-03-31 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "inventory_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("unit", models.CharField(default="pièce", max_length=20)),
                ("prix_achat", models.FloatField(blank=True, null=True)),
                ("prix_vente", models.FloatField(blank=True, null=True)),
                ("seuil_alerte", models.IntegerField(default=10)),
                (
                    "fournisseur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emplacement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="inventory.inventorycategory",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_item",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("entree", "Entrée"),
                            ("sortie", "Sortie"),
                            ("ajust", "Ajustement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("quantite_avant", models.IntegerField()),
                ("quantite_apres", models.IntegerField()),
                ("raison", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movement",
                "ordering": ["-created_at"],
            },
        ),
    ]
