# Generated by Django 6.0.3 on 2026-03-23 10:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius", models.IntegerField(default=100)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bureau", "Bureau"),
                            ("chantier", "Chantier / Terrain"),
                        ],
                        default="bureau",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "work_location",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_location",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "check_out_location",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("check_in_lat", models.FloatField(blank=True, null=True)),
                ("check_in_lng", models.FloatField(blank=True, null=True)),
                ("check_out_lat", models.FloatField(blank=True, null=True)),
                ("check_out_lng", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("late", "En retard"),
                            ("half_day", "Demi-journée"),
                            ("on_leave", "Congé"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to="attendance.worklocation",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "ordering": ["-date", "-check_in"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
