# Generated by Django 6.0.3 on 2026-04-18 15:28

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Présent"),
                    ("absent", "Absent"),
                    ("late", "En retard"),
                    ("half_day", "Demi-journée"),
                    ("on_leave", "Congé"),
                ],
                db_index=True,
                default="present",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="worklocation",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["user", "date"], name="attendance_user_id_d716c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "status"], name="attendance_date_32df9b_idx"
            ),
        ),
    ]
