# Generated by Django 6.0.3 on 2026-04-18 15:28

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        ("attendance", "0002_alter_attendance_date_alter_attendance_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianassignment",
            name="date",
            field=models.DateField(
                db_index=True, default=datetime.date.today, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="technicianassignment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="technicianassignment",
            index=models.Index(
                fields=["technician", "date", "is_active"],
                name="technician__technic_5af495_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="technicianassignment",
            index=models.Index(
                fields=["date", "is_active"], name="technician__date_508d1b_idx"
            ),
        ),
    ]
