# Generated by Django 6.0.3 on 2026-04-20 11:05

import apps.depenses_terrain.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chantiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepenseTerrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_depense",
                    models.CharField(
                        choices=[
                            ("cable", "Câble / Fil"),
                            ("puce", "Puce / Composant"),
                            ("transport", "Transport"),
                            ("repas", "Repas"),
                            ("outil", "Outil / Matériel"),
                            ("fourniture", "Fourniture"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_depense", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("refusee", "Refusée"),
                            ("remboursee", "Remboursée"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("notes_admin", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chantier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses_terrain",
                        to="chantiers.chantier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depenses_terrain_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depenses_terrain",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "depense_terrain",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JustificatifDepense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to=apps.depenses_terrain.models._justif_upload_path
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "depense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justificatifs",
                        to="depenses_terrain.depenseterrain",
                    ),
                ),
            ],
            options={
                "db_table": "justificatif_depense",
            },
        ),
        migrations.AddIndex(
            model_name="depenseterrain",
            index=models.Index(
                fields=["technicien", "statut"], name="depense_ter_technic_c816d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depenseterrain",
            index=models.Index(
                fields=["date_depense"], name="depense_ter_date_de_58b05d_idx"
            ),
        ),
    ]
