# Generated by Django 6.0.3 on 2026-04-18 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chantiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Outil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("perceuse", "Perceuse"),
                            ("viseuse", "Viseuse"),
                            ("tournevis", "Tournevis"),
                            ("marteau", "Marteau"),
                            ("niveau", "Niveau"),
                            ("echelle", "Échelle"),
                            ("cable", "Câble / Rallonge"),
                            ("testeur", "Testeur / Multimètre"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("quantite_totale", models.IntegerField(default=1)),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "outil",
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ReservationOutil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("quantite", models.IntegerField(default=1)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("refusee", "Refusée"),
                            ("en_cours", "En cours"),
                            ("retournee", "Retournée"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chantier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_outils",
                        to="chantiers.chantier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="outillage.outil",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations_outils",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reservation_outil",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["statut", "date_debut"],
                        name="reservation_statut_3ad791_idx",
                    ),
                    models.Index(
                        fields=["technicien", "statut"],
                        name="reservation_technic_ac1be9_idx",
                    ),
                ],
            },
        ),
    ]
