# Generated by Django 6.0.3 on 2026-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outillage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationoutil",
            name="heure_debut",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservationoutil",
            name="heure_fin",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
