# Generated by Django 6.0.3 on 2026-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outillage", "0002_reservationoutil_heure_debut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationoutil",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("approuvee", "Approuvée"),
                    ("refusee", "Refusée"),
                    ("en_cours", "En cours"),
                    ("retour_declare", "Retour déclaré"),
                    ("retournee", "Retournée"),
                ],
                db_index=True,
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
