# Generated by Django 6.0.3 on 2026-04-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LigneDevis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="devis.devis",
                    ),
                ),
            ],
            options={
                "db_table": "ligne_devis",
                "ordering": ["id"],
            },
        ),
    ]
