# Generated by Django 6.0.3 on 2026-03-29 03:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approvisionnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "site",
                    models.CharField(
                        choices=[("Dakar", "Dakar"), ("Mbour", "Mbour")], max_length=50
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvisionnements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approvisionnement",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("montant", models.FloatField()),
                (
                    "categorie",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Transport", "Transport"),
                            ("Carburant", "Carburant"),
                            ("Repas", "Repas"),
                            ("Hébergement", "Hébergement"),
                            ("Matériel", "Matériel"),
                            ("Formation", "Formation"),
                            ("Salaire", "Salaire"),
                            ("Loyer", "Loyer"),
                            ("Eau", "Facture eau"),
                            ("Sonatel", "Facture Sonatel"),
                            ("MainOeuvre", "Main d'œuvre mécanicien"),
                            ("Autre", "Autre"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("date_depense", models.DateField(default=datetime.date.today)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "justificatif",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("notes_admin", models.TextField(blank=True, null=True)),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        choices=[("Dakar", "Dakar"), ("Mbour", "Mbour")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "expense",
                "ordering": ["-created_at"],
            },
        ),
    ]
