# Generated by Django 6.0.3 on 2026-04-01 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "client_libre_nom",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "client_libre_telephone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_prevue", models.DateTimeField()),
                ("date_realisation", models.DateTimeField(blank=True, null=True)),
                ("duree_estimee", models.IntegerField(blank=True, null=True)),
                ("duree_reelle", models.IntegerField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("normale", "Normale"),
                            ("haute", "Haute"),
                            ("urgente", "Urgente"),
                        ],
                        default="normale",
                        max_length=20,
                    ),
                ),
                ("adresse", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_intervention",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("societe", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "representant",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("taches_realisees", models.TextField(blank=True, null=True)),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                ("duree_intervention", models.TimeField(blank=True, null=True)),
                ("observations_technicien", models.TextField(blank=True, null=True)),
                ("id_dvr_nvr", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mdp_dvr_nvr",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qr_code_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("signature_data", models.TextField(blank=True, null=True)),
                (
                    "autres_intervenants",
                    models.ManyToManyField(
                        blank=True,
                        db_table="autres_intervenants_assoc",
                        related_name="interventions_autres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_column="client_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        blank=True,
                        db_column="technicien_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions_technicien",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intervention",
                "ordering": ["-date_prevue"],
            },
        ),
        migrations.CreateModel(
            name="InterventionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_article",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantite", models.IntegerField(default=1)),
                ("quantite_utilisee", models.IntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        db_column="article_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        db_column="intervention_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiels",
                        to="interventions.intervention",
                    ),
                ),
            ],
            options={
                "db_table": "intervention_material",
            },
        ),
    ]
