# Generated by Django 6.0.3 on 2026-04-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interventions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interventionmaterial",
            name="nom_article",
        ),
        migrations.RemoveField(
            model_name="interventionmaterial",
            name="quantite_utilisee",
        ),
    ]
