# Generated by Django 6.0.3 on 2026-04-18 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_callhistory_created_at_and_more"),
        ("interventions", "0002_remove_interventionmaterial_nom_article_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="date_prevue",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="priorite",
            field=models.CharField(
                choices=[
                    ("basse", "Basse"),
                    ("normale", "Normale"),
                    ("haute", "Haute"),
                    ("urgente", "Urgente"),
                ],
                db_index=True,
                default="normale",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("planifiee", "Planifiée"),
                    ("en_cours", "En cours"),
                    ("terminee", "Terminée"),
                    ("annulee", "Annulée"),
                ],
                db_index=True,
                default="planifiee",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["statut", "priorite"], name="interventio_statut_d6ab2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["technicien", "statut"], name="interventio_technic_214b6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervention",
            index=models.Index(
                fields=["date_prevue", "statut"], name="interventio_date_pr_9f2308_idx"
            ),
        ),
    ]
