# Generated by Django 6.0.3 on 2026-04-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="all_day",
            field=models.BooleanField(db_column="allDay", default=False),
        ),
    ]
