# Generated by Django 6.0.3 on 2026-03-18 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "billing_client",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.FloatField(default=0)),
                ("alert_quantity", models.FloatField(default=5)),
                ("unit_price", models.FloatField()),
                ("supplier", models.CharField(blank=True, max_length=120, null=True)),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product",
                "ordering": ["name", "description"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("installation_id", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("tax_rate", models.FloatField(default=0.18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("confirmed", "Confirmée"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "domaine",
                    models.CharField(
                        blank=True,
                        choices=[("NETSYSTEME", "NETSYSTEME"), ("SSE", "SSE")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("discount_percent", models.FloatField(default=0.0)),
                ("discount_amount", models.FloatField(default=0.0)),
                ("advance_amount", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.billingclient",
                    ),
                ),
            ],
            options={
                "db_table": "invoice",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity", models.FloatField(default=1)),
                ("unit_price", models.FloatField()),
                ("tax_rate", models.FloatField(blank=True, null=True)),
                ("discount_percent", models.FloatField(default=0.0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_item",
            },
        ),
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proforma_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("tax_rate", models.FloatField(default=0.18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("converted", "Converti"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "domaine",
                    models.CharField(
                        blank=True,
                        choices=[("NETSYSTEME", "NETSYSTEME"), ("SSE", "SSE")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("converted_to_invoice", models.BooleanField(default=False)),
                ("discount_percent", models.FloatField(default=0.0)),
                ("discount_amount", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proformas",
                        to="billing.billingclient",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_proforma",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "proforma",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProformaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity", models.FloatField(default=1)),
                ("unit_price", models.FloatField()),
                ("tax_rate", models.FloatField(blank=True, null=True)),
                ("discount_percent", models.FloatField(default=0.0)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proforma_items",
                        to="billing.product",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.proforma",
                    ),
                ),
            ],
            options={
                "db_table": "proforma_item",
            },
        ),
    ]
