# Generated by Django 6.0.2 on 2026-03-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="installation_id",
        ),
    ]
