# Generated by Django 6.0.2 on 2026-03-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_invoice_installation_id"),
        ("installations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="factures",
                to="installations.installation",
            ),
        ),
    ]
