# Generated by Django 6.0.3 on 2026-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0004_alter_invoiceitem_description_alter_proformaitem_description",
        ),
        ("installations", "0003_alter_installation_date_installation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("confirmed", "Confirmée"),
                    ("sent", "Envoyée"),
                    ("paid", "Payée"),
                    ("overdue", "En retard"),
                    ("cancelled", "Annulée"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "date"], name="invoice_status_91cac4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["billing_client", "status"], name="invoice_billing_8f9931_idx"
            ),
        ),
    ]
