# Generated by Django 6.0.3 on 2026-04-18 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chantier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin_prevue", models.DateField(blank=True, null=True)),
                ("date_fin_reelle", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chantiers_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chantiers_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "techniciens",
                    models.ManyToManyField(
                        blank=True,
                        db_table="chantier_technicien",
                        related_name="chantiers_technicien",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chantier",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["statut", "date_debut"],
                        name="chantier_statut_cc880f_idx",
                    )
                ],
            },
        ),
    ]
