# Generated by Django 6.0.2 on 2026-03-19 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_remove_invoice_installation_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(max_length=50)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("rccm", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "immatricule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ninea", models.CharField(blank=True, max_length=100, null=True)),
                ("montant_total", models.FloatField()),
                ("montant_avance", models.FloatField(default=0)),
                ("montant_restant", models.FloatField(default=0)),
                ("date_installation", models.DateField(blank=True, null=True)),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Espèce (Comptant)"),
                            ("one_tranche", "1 tranche"),
                            ("two_tranche", "2 tranches"),
                            ("three_tranche", "3 tranches"),
                            ("four_tranche", "4 tranches"),
                            ("five_tranche", "5 tranches"),
                            ("six_tranche", "6 tranches"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("date_echeance", models.DateField(blank=True, null=True)),
                (
                    "contrat_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_commercial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installations_commercial",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "techniciens",
                    models.ManyToManyField(
                        blank=True,
                        db_table="installation_techniciens",
                        related_name="installations_technicien",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "installation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstallationProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.FloatField()),
                ("total_price", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="installations.installation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installation_products",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "db_table": "installation_product",
            },
        ),
    ]
