# Generated by Django 6.0.3 on 2026-04-04 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Versement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.FloatField()),
                (
                    "date_versement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("espece", "Espèce"),
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("mobile", "Mobile Money"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "numero_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("recu_path", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versements",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "db_table": "versement",
                "ordering": ["-date_versement"],
            },
        ),
    ]
