# Generated by Django 6.0.3 on 2026-04-18 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0002_versement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="date_installation",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="montant_restant",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="installation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours"),
                    ("termine", "Terminé"),
                    ("annule", "Annulé"),
                ],
                db_index=True,
                default="en_attente",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="installation",
            index=models.Index(
                fields=["statut", "montant_restant"],
                name="installatio_statut_f8954b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="installation",
            index=models.Index(
                fields=["agent_commercial", "statut"],
                name="installatio_agent_c_5593d1_idx",
            ),
        ),
    ]
