# Generated by Django 6.0.3 on 2026-03-30 11:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("entreprise", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("adresse", models.TextField(blank=True, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "type_client",
                    models.CharField(
                        choices=[("prospect", "Prospect"), ("client", "Client")],
                        default="prospect",
                        max_length=20,
                    ),
                ),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("date_blacklisted", models.DateTimeField(blank=True, null=True)),
                ("note_conversion", models.TextField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converted_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "client",
                "ordering": ["-created_at", "nom"],
            },
        ),
        migrations.CreateModel(
            name="CallHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_1", models.CharField(max_length=20)),
                ("contact_2", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "resultat_appel",
                    models.CharField(
                        choices=[
                            ("client_joint", "Client joint"),
                            ("client_non_joint", "Client non joint"),
                        ],
                        default="client_non_joint",
                        max_length=30,
                    ),
                ),
                ("categorie", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "motif_principal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motif_refus",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "motif_refus_detail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("moratoire", models.CharField(blank=True, max_length=50, null=True)),
                ("commentaires", models.TextField(blank=True, null=True)),
                ("date_appel", models.DateField(default=datetime.date.today)),
                ("date_installation", models.DateField(blank=True, null=True)),
                ("date_maintenance_1", models.DateField(blank=True, null=True)),
                ("date_maintenance_2", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_history",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "call_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientImportHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "client_import_history",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="import_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="clients.clientimporthistory",
            ),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="clients.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminder",
                "ordering": ["-created_at"],
            },
        ),
    ]
