# Generated by Django 6.0.3 on 2026-04-18 15:28

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="callhistory",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="callhistory",
            name="date_appel",
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="callhistory",
            name="resultat_appel",
            field=models.CharField(
                choices=[
                    ("client_joint", "Client joint"),
                    ("client_non_joint", "Client non joint"),
                ],
                db_index=True,
                default="client_non_joint",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="is_blacklisted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="type_client",
            field=models.CharField(
                choices=[("prospect", "Prospect"), ("client", "Client")],
                db_index=True,
                default="prospect",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="callhistory",
            index=models.Index(
                fields=["client", "created_at"], name="call_histor_client__d3bb0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callhistory",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="call_histor_created_f04e61_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_blacklisted", "type_client"],
                name="client_is_blac_68efb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["assigned_to", "is_blacklisted"],
                name="client_assigne_e760c3_idx",
            ),
        ),
    ]
